export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const REGISTER_USER = 'register_user';
export const REGISTER_USER_SUCCESS = 'register_success';
export const REGISTER_USER_FAIL = 'register_fail';
export const AUTHENTICATE = 'authenticate';
export const DEAUTHENTICATE = 'deauthenticate';
export const USER = 'user';
export const CHECK_LOGIN = 'check_login';
export const LOG_OUT = 'LOG_OUT';

export const GET_PRODUCTS_BANNER_SLIDE = 'GET_PRODUCTS_BANNER_SLIDE';
export const GET_PRODUCTS_BANNER_SLIDE_SUCCESS = 'GET_PRODUCTS_BANNER_SLIDE_SUCCESS';
export const GET_PRODUCTS_BANNER_SLIDE_FAIL = 'GET_PRODUCTS_BANNER_SLIDE_FAIL';
export const GET_DATA_USER = 'GET_DATA_USER';
export const GET_DATA_USER_SUCCESS = 'GET_DATA_USER_SUCCESS';
export const GET_DATA_USER_FAIL = 'GET_DATA_USER_FAIL';



export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const UPDATE_PRODUCT_TO_CART = 'UPDATE_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_IN_CART = 'REMOVE_PRODUCT_IN_CART';
export const CHECK_CART = 'CHECK_CART';
export const LOAD_DATA_PRODUCT_REQUEST = 'LOAD_DATA_PRODUCT_REQUEST';
export const LOAD_DATA_PRODUCT_SUCCESS = 'LOAD_DATA_PRODUCT_SUCCESS';
export const LOAD_DATA_PRODUCT_FAIL = 'LOAD_DATA_PRODUCT_FAIL';

export const GET_ORDER_DETAIL_REQUEST = 'GET_ORDER_DETAIL_REQUEST';
export const GET_ORDER_DETAIL_SUCCESS = 'GET_ORDER_DETAIL_SUCCESS';
export const GET_ORDER_DETAIL_FAIL = 'GET_ORDER_DETAIL_FAIL';

export const SEND_COMMENT_PRODUCT_REQUEST = 'SEND_COMMENT_PRODUCT_REQUEST';
export const SEND_COMMENT_PRODUCT_SUCCESS = 'SEND_COMMENT_PRODUCT_SUCCESS';
export const SEND_COMMENT_PRODUCT_FAIL = 'SEND_COMMENT_PRODUCT_FAIL';

export const SAVE_ORDER_REQUEST = 'SAVE_ORDER_REQUEST';
export const SAVE_ORDER_SUCCESS = 'SAVE_ORDER_SUCCESS';
export const SAVE_ORDER_FAIL = 'SAVE_ORDER_FAIL';

export const GET_SIDEBAR_REQUEST = 'GET_SIDEBAR_REQUEST';
export const GET_SIDEBAR_SUCCESS = 'GET_SIDEBAR_SUCCESS';
export const GET_SIDEBAR_FAIL = 'GET_SIDEBAR_FAIL';

export const GET_SEARCH_BY_ID_CATEGORY_REQUEST = 'GET_SEARCH_BY_ID_CATEGORY_REQUEST';
export const GET_SEARCH_BY_ID_CATEGORY_SUCCESS = 'GET_SEARCH_BY_ID_CATEGORY_SUCCESS';
export const GET_SEARCH_BY_ID_CATEGORY_FAIL = 'GET_SEARCH_BY_ID_CATEGORY_FAIL';







